# -*- coding: utf-8 -*-
"""train_rnn_models

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hDMP8Y4CB7vbigeO3x5BfM27IpYAyA6E
"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext autoreload
# %aimport data_creater
# %aimport model
# %autoreload 1

from data_creater import *
from model import *

stocks = companies()
symbols = stocks['Symbol'].values.tolist()
print(symbols)

window_sizes = [5,7,10]
dropouts =  [0.25,0.4]
learn_rates = [0.01,0.001]
epochs = [100,200]
batch_size = 50

result = model_selector(symbols[0], window_sizes, learn_rates, dropouts, epochs, batch_size,verbose=1)

print("\nResults : ")
print("-"*60)
print(result[0])

print(result[1])
ModelLoader.save(result[1]['ticker'],result[0],result[1])
print("Saved trained model for {}".format(result[1]['ticker']))

from keras import backend as K
import tensorflow as tf

for ticker in symbols[1:]:
    #release memory
    K.clear_session()
    tf.reset_default_graph()
    
    result = model_selector(ticker, window_sizes, learn_rates, dropouts, epochs, batch_size,verbose=2)
    
    #save trained model
    ModelLoader.save(result[1]['ticker'],result[0],result[1])
    print(" ==> Saved trained model for {}".format(result[1]['ticker']))